module {
  func.func @func(%arg0: !openfhe.crypto_context, %arg1: !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, %arg2: !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = f16> {
    %cst = arith.constant dense<[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00]> : tensor<8xf64>
    %cst_0 = arith.constant dense<0.0999755859375> : tensor<8xf64>
    %0 = openfhe.mul_no_relin %arg0, %arg1, %arg2 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <dimension = 3, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %1 = openfhe.relin %arg0, %0 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <dimension = 3, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %2 = openfhe.make_ckks_packed_plaintext %arg0, %cst_0 : (!openfhe.crypto_context, tensor<8xf64>) -> !lwe.rlwe_plaintext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>, underlying_type = tensor<8xf16>>
    %3 = openfhe.add_plain %arg0, %1, %2 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_plaintext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %4 = openfhe.rot %arg0, %3 {index = 6 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %5 = openfhe.rot %arg0, %1 {index = 7 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %6 = openfhe.add %arg0, %4, %5 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %7 = openfhe.add %arg0, %6, %1 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %8 = openfhe.rot %arg0, %7 {index = 6 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %9 = openfhe.add %arg0, %8, %5 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %10 = openfhe.add %arg0, %9, %1 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %11 = openfhe.rot %arg0, %10 {index = 6 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %12 = openfhe.add %arg0, %11, %5 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %13 = openfhe.add %arg0, %12, %1 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %14 = openfhe.rot %arg0, %13 {index = 7 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %15 = openfhe.add %arg0, %14, %1 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %16 = openfhe.make_ckks_packed_plaintext %arg0, %cst : (!openfhe.crypto_context, tensor<8xf64>) -> !lwe.rlwe_plaintext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>, underlying_type = tensor<8xf16>>
    %17 = openfhe.mul_plain %arg0, %15, %16 : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>, !lwe.rlwe_plaintext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %18 = openfhe.rot %arg0, %17 {index = 7 : index} : (!openfhe.crypto_context, !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>) -> !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>>
    %19 = lwe.reinterpret_underlying_type %18 : !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = tensor<8xf16>> to !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = f16>
    return %19 : !lwe.rlwe_ciphertext<encoding = #lwe.polynomial_evaluation_encoding<cleartext_start = 16, cleartext_bitwidth = 16>, rlwe_params = <ring = <coefficientType = !mod_arith.int<463187969 : i32>, polynomialModulus = <1 + x**8>>>, underlying_type = f16>
  }
  func.func @func__generate_crypto_context() -> !openfhe.crypto_context {
    %0 = openfhe.gen_params  {mulDepth = 2 : i64, plainMod = 4295294977 : i64} : () -> !openfhe.cc_params
    %1 = openfhe.gen_context %0 : (!openfhe.cc_params) -> !openfhe.crypto_context
    return %1 : !openfhe.crypto_context
  }
  func.func @func__configure_crypto_context(%arg0: !openfhe.crypto_context, %arg1: !openfhe.private_key) -> !openfhe.crypto_context {
    openfhe.gen_mulkey %arg0, %arg1 : (!openfhe.crypto_context, !openfhe.private_key) -> ()
    openfhe.gen_rotkey %arg0, %arg1 {indices = array<i64: 6, 7>} : (!openfhe.crypto_context, !openfhe.private_key) -> ()
    return %arg0 : !openfhe.crypto_context
  }
}
